server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname} :${spring.application.instance_id :${random.value}}
  client:
    ## EUREKA ????? ?????? ??? ????? ????(true)
    register-with-eureka: true
    fetch-registry: true
    # EUREKA ?? url
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
